= Лабораторная работа №7
Волбенко В.Д. <КЭ-413>
:description: Лабораторная работа №7
:toc:
:toc-title: Оглавление
:imagesdir: Pic
:figure-caption: Рисунок
:table-caption: Таблица

include::Titul7.adoc[]

== Основная информация про вcтроенные таймеры для платы STM32F411RET6

STM32F411RET6 — это мощная микроконтроллерная плата на базе ядра ARM Cortex-M4, и одной из её ключевых особенностей являются встроенные таймеры. Таймеры — это аппаратные модули, которые позволяют микроконтроллеру измерять время, генерировать сигналы или выполнять задачи через определённые интервалы времени.

Эта плата оснащена несколькими типами таймеров, которые отличаются друг от друга по возможностям. Одни из них ориентированы на базовые задачи, например, подсчёт времени или создание задержек. Другие более сложные, например, для работы с сигналами ШИМ (широтно-импульсная модуляция) или для захвата и сравнения внешних событий, таких как импульсы от кнопок или датчиков.

Сами таймеры работают на основе тактового сигнала микроконтроллера. Это значит, что они считают импульсы, приходящие от генератора частоты, и используют эти данные, чтобы отслеживать время или генерировать сигналы с точными интервалами. Например, можно настроить таймер так, чтобы он «перезапускался» каждые 10 миллисекунд и сообщал программе о наступлении этого события. Такие механизмы полезны для создания точных задержек или периодических задач, например, мигания светодиодов или опроса датчиков.

Также в STM32F411RET6 есть таймеры, которые позволяют управлять двигателями или другими устройствами, где требуется точная генерация сигналов. Они могут генерировать сигналы с разными уровнями напряжения (ШИМ), что даёт возможность плавно регулировать скорость вращения двигателя или яркость светодиода.

=== Таймеры

а STM32F411RET6 есть несколько типов таймеров, каждый из которых предназначен для определённых задач. Они делятся на общие таймеры, таймеры для ШИМ и энкодеров, а также системные таймеры. Вот их основные категории и примеры таймеров:

. Общие таймеры (General-purpose timers), Эти таймеры универсальны и могут использоваться для множества задач, таких как создание задержек, измерение времени, генерация сигналов ШИМ (широтно-импульсной модуляции) или работа с внешними событиями. На STM32F411RET6 есть следующие такие таймеры:

* TIM2 и TIM5: 32-битные таймеры. Это значит, что они могут считать дольше, прежде чем «переполниться» (сбросить счётчик). Они удобны для работы с длительными интервалами времени или для задач, требующих высокой точности.
* TIM3, TIM4: 16-битные таймеры. Эти таймеры более компактные, их хватает для большинства обычных задач, таких как генерация ШИМ-сигналов или измерение коротких временных интервалов.

. Таймеры для управления двигателями (Advanced-control timer), Это более мощные и специализированные таймеры, которые могут одновременно управлять несколькими каналами, что делает их подходящими для управления двигателями или генерации сложных ШИМ-сигналов:

* TIM1: Расширенный 16-битный таймер. Он имеет дополнительные функции, такие как мёртвое время (dead-time) и возможность синхронизации нескольких выходных каналов. Эти возможности особенно полезны в системах управления двигателями.

.  Системный таймер (SysTick) — это специальный таймер, встроенный в ядро Cortex-M4. Его основная задача — обеспечить высокоточную генерацию прерываний с фиксированным интервалом. Например, его часто используют в операционных системах реального времени (RTOS) для управления задачами. SysTick не требует сложной настройки и работает независимо от других таймеров.

. Таймер для реального времени (RTC), Хотя RTC (Real-Time Clock) не является классическим таймером, он используется для работы с длительными интервалами времени и отслеживания текущего времени (часы, минуты, секунды). Этот модуль позволяет поддерживать время даже при отключении питания, если подключена резервная батарея.

. Таймеры с возможностью работы в режиме захвата и счётчика-кодера, такие как TIM2, TIM3, TIM4 и TIM5, поддерживают режимы, которые позволяют:

* Измерять временные интервалы между внешними событиями (Input Capture).
* Работать как счётчики энкодеров (например, отслеживание вращения ручек или колёс).

Эти таймеры гибки в настройке и могут быть запрограммированы на работу в различных режимах, включая генерацию ШИМ, измерение частоты сигналов и работу с энкодерами.

=== Таймеры TIM2 и TIM5, основные особенности
* Таймеры 32 битные (то есть могут считать до 2^32), умеют работать:
- с инкрементальными энкодерами и датчиками Холла,
- несколько таймеров можно синхронизировать между собой.

* Таймеры могут использоваться для:
- Захвата сигнала (Защелкивать значение, когда на выводе порта например 0 сменился на 1)
- Сравнения (Считать до значения в регистре сравнения и установить/сбросить/переключить вывод порта)
- Генерации ШИМ (Генерировать прямоугольный сигнал с различной скважностью на вывод порта)
- Генерации одиночного импульса

=== Таймеры TIM2 и TIM5
* Таймеры могут генеририровать следующие события:
** Переполнение
** Захват сигнала
** Сравнение
** Событие-триггер

=== Таймеры TIM2 и TIM5 начальная запуск
* Таймеры тактируются от шины APB1.

== Работа с системным таймером

Системный таймер SysTick, встроенный в ядро ARM Cortex-M4 микроконтроллеров STM32, используется для создания прерываний с заданной периодичностью. Для его подключения и настройки используются следующие шаги и команды:

[source, cpp]
----
#include "stkregisters.hpp" // for SystemTimer
#include "scbregisters.hpp" // for ISCR register
----

Далее приведен код, который реализует функцию задержки на заданное количество миллисекунд с использованием системного таймера (SysTick) и была  реализована функция delay().

[source, cpp]
----

void delay(uint32_t mseconds)
{
  assert (mseconds < 10000);
  const auto timerDelayCounts = (SystemCoreClock / 1000U) * mseconds;
  STK::LOAD::Write(timerDelayCounts - 1);
  STK::VAL::Write(0);
  STK::CTRL::ENABLE::Enable::Set();

    while(STK::CTRL::COUNTFLAG::NoOverflow::IsSet())
    {
    }
  
   STK::CTRL::ENABLE::Disable;
}

----

Код main():

[source, cpp]
----

int main()
{  
  RCC::AHB1ENR::GPIOAEN::Enable::Set() ;
  RCC::AHB1ENR::GPIOCEN::Enable::Set() ;
  GPIOA::MODER::MODER5::Output::Set() ;
  GPIOC::MODER::MODER5::Output::Set() ;
  GPIOC::MODER::MODER8::Output::Set() ;
  GPIOC::MODER::MODER9::Output::Set() ;
  
  Button <GPIOC, 13> button;

  Led<GPIOC, 5> led1;
  Led<GPIOC, 8> led2;
  Led<GPIOC, 9> led3;
  Led<GPIOA, 5> led4;
  
   tLeds leds = {
    &led1,
    &led2,
    &led3,
    &led4};
    
    
    AllMode allmode(leds);
    ChessMode chessmode(leds);
    TreeMode treemode(leds);
    
    tMode MODES = {
    &allmode,  
    &chessmode,
    &treemode  
    };
    ModeManager modeManager(MODES);
    modeManager.InitModeManager();

  for(;;) 
  {

    modeManager.UpdateModeManager();
    
    if(button.isClick())
    {
      modeManager.SwitchModeManager();
    }
    delay(300);
  }
    
  return 1;
}

----

== Настройка таймера TIM5

Таймер TIM5 в микроконтроллере STM32F411RET6 — это 32-битный универсальный таймер, встроенный в микроконтроллер для выполнения задач, связанных с временными интервалами, сигналами и событиями.

Основные характеристики TIM5:

* 32-битный счётчик. Поддержка больших интервалов времени или высокой точности.

* Частота работы. Таймер может работать на частоте до 84 МГц, что соответствует тактовой частоте микроконтроллера.

* 4 канала. Каждый канал можно использовать для генерации ШИМ-сигналов, захвата внешних сигналов или других задач.
 
* Аппаратная поддержка. Поддерживает прерывания и события без вмешательства процессора.

* Режимы работы. Генерация периодических сигналов, ШИМ, захват/сравнение сигналов, счёт импульсов, работа с энкодерами.

Применения TIM5: 

* Генерация временных интервалов.

* Широтно-импульсная модуляция (ШИМ).

* Захват входных сигналов (Input Capture).

* Работа с энкодерами.

* Счёт внешних импульсов.

Основные регистры TIM5:

. PSC (Prescaler): Делитель частоты входного сигнала.
. ARR (Auto Reload Register): Устанавливает период счётчика.
. CNT (Counter): Хранит текущее значение счётчика.
. CCR1–CCR4: Управляют каналами захвата/сравнения.
. CR1: Настройка основных параметров таймера.
. DIER: Разрешение прерываний и DMA-запросов.
. SR: Флаги состояния таймера. 

Разработка функции delay() на основе таймера TIM5.

Подключение таймера:

[source, cpp]
----
#include "tim5registers.hpp"

std::uint32_t SystemCoreClock = 16'000'000U;

extern "C" {
int __low_level_init(void)
{
  RCC::CR::HSION::On::Set();
  while (RCC::CR::HSIRDY::NotReady::IsSet())
  {

  }
  RCC::CFGR::SW::Hsi::Set();
  while (!RCC::CFGR::SWS::Hsi::IsSet())
  {

  }
  RCC::APB1ENR::TIM5EN::Enable::Set();
  return 1;
}
----


Функция осуществляет задержку с использованием таймера TIM5 микроконтроллера. Она проверяет входное значение mseconds на корректность, затем настраивает таймер: задаёт предделитель для работы с миллисекундами, устанавливает значения регистров автоперезагрузки (ARR) и счётчика (CNT), сбрасывает флаг прерывания (UIF) и запускает таймер. После этого функция в цикле ожидает окончания заданного времени, проверяя состояние флага прерывания. По завершении задержки таймер отключается, а флаг прерывания сбрасывается:

[source, cpp]
----
void delay(uint32_t mseconds)
{
  assert (mseconds < 10000);
  const auto timerDelayCounts = (SystemCoreClock / 1000U) * mseconds;
  TIM5::PSC::Write(timerDelayCounts-1U);
  TIM5::CR1::URS::Value1::Set();
  TIM5::ARR::Write(mseconds);
  TIM5::CNT::Write(0);
  TIM5::SR::UIF::Set(0);
  TIM5::CR1::CEN::Enable::Set(); 
    while(TIM5::SR::UIF::NoInterruptPending::IsSet())
    {
    }
   TIM5::CR1::CEN::Disable::Set();
   TIM5::SR::UIF::Set(0);
}
----

== Вывод по работе:

В данной работе были рассмотренны основные таймеры в микроконтроллере STM32F411RET6, их типы и примеры использования. Была проделана работа с системным таймером. Также был настроен таймер TIM5 с функцией delay().